#
# Dockerfile for 360Atlas
#

FROM ubuntu:16.04

RUN apt-get upgrade
RUN apt-get upgrade -y

RUN apt-get install -y wget

RUN apt-get install -y mysql-client-5.6

RUN wget http://oa.shengyisoft.com/Atlas-2.2-debian7.0-x86_64.deb
RUN dpkg -i  Atlas-2.2-debian7.0-x86_64.deb

RUN apt-get remove -y wget

VOLUME /usr/local/mysql-proxy/conf/docker-atlas.cnf

EXPOSE 1234
EXPOSE 2345

CMD /usr/local/mysql-proxy/bin/mysql-proxyd docker-atlas start

CMD tail -f /usr/local/mysql-proxy/log/docker-atlas.log